### PR TITLE
add sql for meals 18-23,38-47

### PR DESCRIPTION
**Pull request by nikitkokatsiaryna**
Added SQL for meals 18-23, 38-47 from "Recipe list" file

has been fixed in new PR:
1. added several tags to the dish
2. added photos and videos of the dish
3. added additional instructions to cooking 
4. fixed cooking_duration
5. added measurement measures. For everything that is convenient to measure with cups (mostly liquid products), cups are used. OZS is used for main courses
6. extra syntax has been eliminated (part with "value" merged)
7. added the size of portions and their total number where it was not originally specified

### CODE REVIEW

**Comment by rorybray** [comment]
I don't see an issue for this, is there one?

**Comment by rorybray** [comment]
Also this is a PR into `develop`, should it be a PR into `V2` instead?

**Comment by nikitkokatsiaryna** [comment]
> I don't see an issue for this, is there one?

I have corrected all the comments from Pujitha and am waiting for approval

**Comment by shanthisa** [comment]
Closing it. Please create PR to v2

**Pull request closed without merging**
