### PR TITLE
632 terms and conditions page

### LINKED ISSUE #632: [FEATURE] Terms and conditions page
**Is your feature request related to a problem? Please describe.**
A Terms and conditions page that displays a set text and the user needs to click a checkbox 'I read the terms and conditions' and click on Agree. Without which we will not allow access to the app and we will logout.

**Describe the solution you'd like**
As a user atleast one time the user needs to agree to the terms and conditions of the application in their first login. If they are already registered like in our production environment, we need to present it next time they login.

**Additional context**
We need to insert a column terms and conditions flag in users table. This should be set to true when the user agrees. By default it would be false. We need a terms and conditions page with text that displayed and checkbox that says 'I read the terms and conditions' and then a button 'Agree' and button 'Disagree'. If they disagree, they will be logged out. If they agree they will get it. This should only be once for the user not each time of login.

### PR DESCRIPTION
**Pull request by priyaguntupalli5**
[Screencast from 04-26-2024 07:52:28 PM.webm](https://github.com/CivicTechFredericton/mealplanner/assets/97687268/534f730c-03df-4ed8-9bf4-d471524311b2)

**Describe the technical changes contained in this PR**
Created a new end point named terms in App.tsx file for terms and conditions page. Added terms and conditions field in the person and current user. 

**Previous behaviour**
There was no terms and conditions earlier.

**New behaviour**
created a new end point named terms to display terms and conditions. Loggedin person can only access the application if they accept the terms and conditions else, they will be logged out.

**Related issues addressed by this PR**
Fixes #632 

**Have the following been addressed?**
- [ ] Have test cases been created for all of the changes?
- [ ] Do all of the test cases pass?
- [ ] Has the testing been done using the default docker-compose environment?
- [ ] Are documentation changes required?
- [ ] Does this change break or alter existing behaviour?

### CODE REVIEW

**Review by shanthisa — CHANGES_REQUESTED** [review]
There is a security vulnerability here. When you are in the /terms page, you delete the '/terms' in the url and type /mealplans, it will re-route to mealplans. This should not happen. /terms page should be the only page visible if the terms and conditions are not yet accepted to the user. That code is missing. Please fix that.

**Comment by shanthisa** [comment]
The end points are not working correctly, and this needs to be fixed. Please refer to the video below to understand the issues.

https://github.com/CivicTechFredericton/mealplanner/assets/57197486/f086e401-16e3-42e8-86f8-cf46870fe46f

**Comment by RLCASTRO** [comment]
the solution for this issue will continue in the PR #674

**Comment by shanthisa** [comment]
Closing this as @RLCASTRO fixed this as part of PR #674

**Pull request closed without merging**
